BLOG_MEDIA_ENABLED = False

BLOG_MARKUP_ENABLED = True

BLOG_CATEGORIES_ENABLED = True

BLOG_COMMENTS_ENABLED = True

BLOG_AUTO_CLOSE_COMMENTS_DAYS = 60

BLOG_FEEDS_ENABLED = True

BLOG_FEED_TITLE = 'Skel Blog Feed'

BLOG_FEED_DESCRIPTION = 'Skel Blog Feed'

BLOG_FEED_NUM_ITEMS = 10

BLOG_FEED_SHOW_AUTHOR_EMAIL = False

BLOG_FEED_CATEGORY_TITLE = '%s - %%(category)s Category' % BLOG_FEED_TITLE